pool:
  name: Hosted VS2017
  demands:
  - MSBuild
  - Xamarin.Android
  - msbuild
  - vstest
  - java
  - JDK

variables:
  BuildConfiguration: 'Release'
  Parameters.restorePkgSolution: '**\*.sln'
  Parameters.appFiles: '$(build.binariesdirectory)/$(BuildConfiguration)/*.apk'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.restorePkgSolution)'

- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android project'
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: '$(BuildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Set-Content -Value "apiKey=a452180f174846a493e8f1abad8ee093abd66fb665a24a50a9016db08a02fdbc" -Path ./eua.config
      Add-Content -Value "userKey=1261b5af19e940e2bbb63fc0208cc77f7e24a9bc83874853b6f6eb2585990c99" -Path ./eua.config
      Add-Content -Value "productName=Xamarin" -Path ./eua.config
      Add-Content -Value "projectName=PerfectBody" -Path ./eua.config
      Add-Content -Value "enableImpactAnalysis=true" -Path ./eua.config
      Add-Content -Value "requireKnownSha1=false" -Path ./eua.config
      Add-Content -Value "resolveAllDependencies=false" -Path ./eua.config
      Add-Content -Value "nuget.resolveDependencies=true" -Path ./eua.config
      Add-Content -Value "nuget.runPreStep=true" -Path ./eua.config
      Add-Content -Value "fileSystemScan=false" -Path ./eua.config
      Add-Content -Value "includes=**/*.dll **/*.exe" -Path ./eua.config
      Add-Content -Value "excludes=**/tests/**" -Path ./eua.config
      Add-Content -Value "enableImpactAnalysis=true" -Path ./eua.config
      Get-Content -Path ./eua.config
  displayName: 'Create whitesource config'
  
- script: |
    curl -LJO https://github.com/whitesource-ft/xModuleAnalyzer-NET/blob/main/xModuleAnalyzer-NET.ps1
    echo "xModuleAnalyzer-NET downloaded successfully"
    
- task: PowerShell@2
  inputs:
    filePath: './xModuleAnalyzer-NET.ps1'
    arguments: '-d ./ -c ./eua.config'
  displayName: 'Unified Agent Prioritize Scan'
  
